# Hyde Jekyll Theme Configuration
# See: https://github.com/poole/hyde

# Site settings
title: Victoria Shi
tagline: Personal Website
description: >
  BSc Neuroscience, MSc Biomedical Engineering

# Author information
author:
  name: Victoria Shi
  email: your.email@example.com
  github: shivictoria
  twitter: your-twitter-handle
  linkedin: yuenvictoriashi

# URL settings
url: "https://your-domain.com"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  projects:
    output: true
    permalink: /portfolio/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Your Name"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author: "Your Name"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 